### ISSUE TITLE
Error parsing destination, destination plugin http not found

### ISSUE THREAD

**Issue by zsarosi** [abalage/balagetech-openwrt-syslog-ng-elasticsearch#1]
Hi Balázs

I used your syslog-ng config, it worked for a week or two, but since a couple of days it stopped working, without any changes in the configs. If I start it manually it returns:

```
# /usr/sbin/syslog-ng 
Error parsing destination, destination plugin http not found in /etc/syslog-ng/conf.d/network.conf at line 113, column 5:
                                                  included from /etc/syslog-ng/syslog-ng.conf line 162, column 1

        template("$(format_json --pair host.name=$HOST --pair host.ip=$SOURCEIP --pair @timestamp=$ISODATE --pair message=$MESSAGE --pair tags=openwrt --pair ecs.version=1.0.0 --key host.* --key event.* --key inbound.s* --key inbound.d* --key outbound.s* --key outbound.d* --key network.*)\n")
    ^^^^


syslog-ng documentation: https://www.balabit.com/support/documentation?product=syslog-ng-ose
contact: https://lists.balabit.hu/mailman/listinfo/syslog-ng
```

Of course I tried to install syslog-ng-mod-http, but my repository does not have this package and the other repository here http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04/ didn't help either.
It is strange, that I never had the package syslog-ng-mod-http but the very same config was working for several days and it suddenly died on 04.04.2020....
On 04.04.2020 the following packages were updated: libgd3_2.2.5-4ubuntu0.4_armhf.deb and containerd_1.3.3-0ubuntu1~18.04.2_armhf.deb nothing else.

My config:
odroid XU4 with ubuntu 18.04
syslog-ng 3.13.2-3 
Kernel release: 4.14.111-158
Architecture: armv7l

**Comment by abalage** [comment]
Hi,

László Budai's repo does have that module.
http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04/amd64/syslog-ng-mod-http_3.15.1-1_amd64.deb

I have heard about it that Ubuntu repos do not have that package. [1]
Do you have http module listed in the output of syslog-ng -V?

```
# syslog-ng -V | grep Available-Modules | sed 's/,/\r\n/g' | grep http
http
#
```

If you do not have that, then either try to find and ARM build somewhere or you should build syslog-ng for yourself.

[1] https://stackoverflow.com/questions/58595487/what-is-the-reason-of-syslog-ng-error-destination-plugin-http-not-found

**Comment by zsarosi** [comment]
Unfortunately the http module is missing from the "all" architecture and there is no armv7l arch.
Is it then an anomaly that it used to be working without the http module?

**Comment by abalage** [comment]
Yeah I know it could be pain to compile and maintain it yourself. I did it for myself before I migrated to x86_64 from ARMv7.

I could make theories but without more information about your system's history, they would be just theories.
Let's say probably there were some high sunspot activity which broke it. :) Deal?
