### ISSUE TITLE
Unknown type specified in type hinting: list

### ISSUE THREAD

**Issue by recoil1992** [abalage/balagetech-openwrt-syslog-ng-elasticsearch#2]
Hello,
this is awesome tutorial I was looking for longer time.
Nevertheless while to trying to get to the satisfactory result, I am dealing with issue where the syslog-ng is refusing to start due to error in network-ulogd2.conf.
The error says "Unknown type specified in type hinting: list"

Full error:
Error parsing config, Error compiling template (Unknown type specified in type hinting: list) in /etc/syslog-ng/conf.d/network-ulogd2.conf:
32              timeout(600)
33          );
34      };
35
36      template t_network {
37---->     template("$(format_json --pair host.name=$HOST --pair host.hostname=$HOST --pair host.ip=$SOURCEIP --pair @timestamp=$ISODATE --pair ecs.version=1.5.0 --key host.* --key event.* --key source.* --key destination.* --key network.* tags=list($tags) event.category=list(${event.category}) event.type=list(${event.type}))\n");
37---->              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
38      };
39
40      destination d_elastic_network {
41          elasticsearch-http(
42              url("http://'elastic_host'/_bulk")

**Comment by abalage** [comment]
Hi, 

Thanks for reporting it.
List support was introduced in [syslog-ng-3.20.1](https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-3.20.1). Make sure you are using at least this version or later.

Regards,

**Comment by recoil1992** [comment]
Thank you for useful hint.
Unfortunately raspbian on raspi4 saying 'syslog-ng is already the newest version (3.19.1-5)'. So I will need to wait for official version to be upgraded.

I also think that there is missing one quote in network-ulogd2.conf, line 27
destination_port='${destination.port}; ... should be? ... destination_port='${destination.port}';
Not sure what might be consequence for running code as it is not working for me as whole :-), so just letting you know.

Again, many thanks for your great effort and help.

**Comment by abalage** [comment]
Nice catch. I'll fix it. :)
Fortunately that is a cosmetic bug. That part formats a new log message which will be created by the correlation engine. Syntactically it is valid from configuration point of view.
